global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-apps"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["127.0.0.1:8080", "127.0.0.1:8081", "127.0.0.1:8082"]